# Generated by Django 5.1.2 on 2024-11-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlerating',
            options={'verbose_name': 'Оценка статьи', 'verbose_name_plural': 'Оценки статьи'},
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['date'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='commentrating',
            options={'verbose_name': 'Оценка комментария', 'verbose_name_plural': 'Оценки комментария'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
